Config = Config or {}

Config.PhoneApps = {
    ['settings'] = {
        app = "settings",
        color = "#e24233",
        icon = "fa fa-cog",
        style = "padding-left: 12px !important;",
        tooltipText = "Instellingen",
        slot = 1,
    },
    ['messages'] = {
        app = "messages",
        color = "#00cd77",
        icon = "fas fa-comment-dots",
        style = "padding-left: 12px !important;",
        tooltipText = "Berichten",
        slot = 2,
    },
    ['contacts'] = {
        app = "contacts",
        color = "#ff8f1a",
        icon = "fa fa-address-book",
        style = "padding-left: 13px !important;",
        tooltipText = "Contacten",
        slot = 3,
    },
    ['notes'] = {
        app = "notes",
        color = "#858edd",
        icon = "fa fa-sticky-note",
        style = "padding-left: 13px !important;",
        tooltipText = "Notitie's",
        slot = 4,
    },
    ['bank'] = {
        app = "bank",
        color = "#e2c833",
        icon = "fas fa-university",
        style = "padding-left: 12px !important;",
        tooltipText = "Maze Bank",
        slot = 5,
    },
    ['garage'] = {
        app = "garage",
        color = "#ff8f1a",
        icon = "fas fa-warehouse",
        style = "padding-left: 9px !important;",
        tooltipText = "Voertuigen",
        slot = 6,
    },
    ['mails'] = {
        app = "mails",
        color = "#e24233",
        icon = "fas fa-envelope",
        style = "padding-left: 11px !important;",
        tooltipText = "Mail",
        slot = 7,
    },
    ['twitter'] = {
        app = "twitter",
        color = "#1da1f2",
        icon = "fab fa-twitter",
        style = "padding-left: 12px !important;",
        tooltipText = "Twitter",
        slot = 8,
    },
}